version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorturl-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Hly@1234
      - DB_NAME=shorturl
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_strong_password
    depends_on:
      - mysql
      - redis
    networks:
      - shorturl-network

  mysql:
    image: mysql:8.0
    container_name: shorturl-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_strong_password
      - MYSQL_DATABASE=shorturl
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shorturl-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0-alpine
    container_name: shorturl-redis
    restart: always
    command: redis-server --requirepass your_strong_password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - shorturl-network

networks:
  shorturl-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: